This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./compile-test.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file compile-test.acn....done (305 entries accepted, 0 rejected).
Sorting entries.....done (2674 comparisons).
Generating output file compile-test.acr....done (639 lines written, 0 warnings).
Output written in compile-test.acr.
Transcript written in compile-test.alg.
