# Converts latex acronym format to a rough markdown template for easier viewing
name: Markdown / Latex Acronym Workflow

# CI Variables
env:
  COMPILED: compiled # Compiled Documents Branch Name

on:
  push:
  pull_request:
    types: [opened, reopened, edited, synchronize]

  workflow_dispatch:

# Runs script and uploads new version if in main for markdown output
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v6
        with: 
          fetch-depth: 0

      - name: Import Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-xetex texlive-fonts-recommended texlive-fonts-extra texlive-lang-greek

      - name: Run Markdown Script
        run: |
          rm -f uasal-acronyms.md
          python utilities/latex_acronyms-to-markdown.py

      - name: Upload Markdown Artifact
        uses: actions/upload-artifact@v4
        # Upload even if it fails to better see issues
        if: always()
        with:
          name: Markdown-Acronyms
          path: uasal-acronyms.md
          retention-days: 7

      - name: Run LaTeX Script
        run: |
          git status
          git branch -a
          bash compile.sh

      - name: Upload LaTeX Artifact
        uses: actions/upload-artifact@v4
        # Upload even if it fails to better see issues
        if: always()
        with:
          name: Latex-Acronyms-PDF
          path: compiled-acronyms.pdf

      - name: Extract branch name
        shell: bash
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Update README.md
        if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'pull_request' }}
        run: |
          git fetch                         # fetch branches
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff-index --quiet HEAD ||  git commit -m "Updating README.md for markdown adjustments"  # commit to the repository (ignore if no modification)
          git push # push to remote branch


      - name: Update Compiled Branch
        if: ${{ (github.ref == 'refs/heads/main') || ( github.head_ref != '' ) }}
        run: |
          git fetch origin compiled  --recurse-submodules=no  
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git branch --track ${{env.COMPILED}}  origin/${{env.COMPILED}}        
          mkdir output
          git worktree add output ${{env.COMPILED}}  

          echo "Checking trigger condition for workflow..."
          if [[ "${{github.ref_name}}" == "main" ]]; then
            echo "Running steps for main branch"
            mv *.pdf  output/
            mv *acronyms.md output/
          elif [[ "${{ github.head_ref}}" != '' ]]; then
            mkdir -p output/Pull_Requests/${{github.event.pull_request.number}}
            mv *.pdf  output/
            mv *acronyms.md output/
          else
            echo "Unknown exception hit that shouldn't be allowed unless CI variables or Trigger cases have been adjusted in compiled.yml"
          fi

          echo "Moving worktree and git adding."
          cd output                                            
          git add .                                         
          git commit -m "Compiled documentation from ${{github.ref_name}}"                        
          git push  
        shell: bash
        